<?php

namespace ItNut\ItNutBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByShortCode($shortcode)
    {
        $query = $this->createQueryBuilder('p')
        ->where('p.shortcode = :shortcode')
        ->setParameter('shortcode', $shortcode);
        return $query->getQuery()->getSingleResult();
    }
}
